### ISSUE TITLE
Schema: Property `choices` only allows objects but should also allow arrays

### ISSUE THREAD

**Issue by bhberson** [zapier/zapier-platform-cli#124] opened 2017-08-23 14:08 UTC
Within the [FieldsSchema](https://github.com/zapier/zapier-platform-schema/blob/v1.0.3/docs/build/schema.md#fieldschema) the property `choices` only allows an Object to be passed into it. This is causes problems as if a user is trying to show a static dropdown for example, there is **no** possible way for the dev to sort this as Javascript doesn't guarantee sorting within Objects.

**Comment by BrunoBernardino** [comment] 2017-08-23 14:12
Closing as duplicate of https://github.com/zapier/zapier-platform-cli/issues/125 (though that was created 1 minute later, it has more info). Thanks @bhberson

**Closed by BrunoBernardino** 2017-08-23 14:12 UTC
