### ISSUE TITLE
Weird error message

### ISSUE THREAD

**Issue by escopecz** [zapier/zapier-platform-cli#249] opened 2018-02-22 16:45 UTC
[current version 5.0.0]

If a trigger receives some list with 2 equal IDs, it will throw this message:

```
CheckError: Invalid API Response:
  - Got a two or more results with the id of subsmitted
What happened:
  Executing triggers.tags.operation.perform with bundle
  Invalid API Response:
  - Got a two or more results with the id of subsmitted
      at checkOutput (node_modules/zapier-platform-core/src/app-middlewares/after/checks.js:37:15)
      at Object.collector.then.newOutput (node_modules/zapier-platform-core/src/middleware.js:80:37)
  From previous event:
      at afters.reduce (node_modules/zapier-platform-core/src/middleware.js:77:26)
      at Array.reduce (native)
      at afterMiddleware (node_modules/zapier-platform-core/src/middleware.js:76:21)
      at Object.resolve.then.then.output (node_modules/zapier-platform-core/src/middleware.js:94:18)

  From previous event:
      at Object.beforeMiddleware.then.newInput (node_modules/zapier-platform-core/src/middleware.js:92:10)
      at bound (domain.js:280:14)
      at Object.runBound (domain.js:293:12)
  From previous event:
      at input (node_modules/zapier-platform-core/src/middleware.js:89:45)
      at Domain.handlerDomain.run (node_modules/zapier-platform-core/src/tools/create-lambda-handler.js:91:14)
      at Domain.run (domain.js:221:14)
      at handler (node_modules/zapier-platform-core/src/tools/create-lambda-handler.js:82:19)
      at ZapierPromise (node_modules/zapier-platform-core/src/tools/create-app-tester.js:11:7)
  From previous event:
      at event (node_modules/zapier-platform-core/src/tools/create-app-tester.js:10:12)
      at node_modules/zapier-platform-core/src/tools/create-app-tester.js:45:12
```

I think there is a typo `subsmitted`, but over all the message isn't clear of what's going on. I'd suggest something like:

> Invalid API Response: Got a two or more results with the same id.

**Comment by xavdid** [comment] 2018-02-22 21:49
Hey there @escopecz, thanks for writing in! 

the line that generates that message is [here](https://github.com/zapier/zapier-platform-core/blob/master/src/checks/trigger-has-unique-ids.js#L26) and is verifying that all objects returned from a trigger have unique ids. It seems like two of your objects both have the id `"subsmitted"`, which is something you'll need to fix in scripting. 

We're doing a pass on those messages though, so we'll make sure they're clear about what the issue is!

**Comment by escopecz** [comment] 2018-02-23 07:43
Oh, so the typo was in my testing data. Good to know. Maybe quotation marks would make it clearer.

**Comment by xavdid** [comment] 2018-03-02 05:50
this was addressed in https://github.com/zapier/zapier-platform-core/pull/67. thanks for the report!

**Closed** 2018-03-02 05:50 UTC
