### ISSUE TITLE
Windows: zapier push fails because build's node_modules folder is empty

### ISSUE THREAD

**Issue by biaoqianwo** [zapier/zapier-platform-cli#82] opened 2017-05-19 02:52 UTC
```
C:\Program Files\nodejs\node_modules\npm\zapier-example>zapier push --debug
Preparing to build and upload your app.

>> GET https://zapier.com/api/platform/cli/check
<< 200
<< {"success": true}

  Copying project to temp directory     done!
  Installing project dependencies .

Running npm.cmd install --production command in C:\Users\allen\AppData\Local\Te
p\zapier-536ab35f:

..


    done!
  Applying entry point file ...
Error: : File C:\Users\allen\AppData\Local\Temp\zapier-536ab35f/node_modules/za
ier-platform-core/include/zapierwrapper.js not found.
    at C:\Users\allen\AppData\Roaming\npm\node_modules\zapier-platform-cli\lib\
tils\files.js:31:11

Error!

```
```
C:\Program Files\nodejs\node_modules\npm\zapier-example>npm version
{ 'zapier-platform-example-app-trigger': '1.0.0',
  npm: '4.6.1',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.9.1',
  openssl: '1.0.2j',
  uv: '1.9.1',
  v8: '5.1.281.84',
  zlib: '1.2.8' }

```

**Comment by FokkeZB** [comment] 2017-08-24 07:05
Another user experience the same issue and found that the `node_modules` folder in the temp folder holding the build was empty:

<img width="537" alt="capture" src="https://user-images.githubusercontent.com/2699409/29653786-4d681b94-88ab-11e7-8c8c-7cd71ac1bd07.png">
<img width="502" alt="capture2" src="https://user-images.githubusercontent.com/2699409/29653787-4d68aeba-88ab-11e7-91e3-3f8878ba5cc6.png">

**Comment by FokkeZB** [comment] 2017-08-24 07:33
The related code is:
https://github.com/zapier/zapier-platform-cli/blob/493c2cbff27b058cb6553d9dd9cbe10b2eddad60/src/utils/build.js#L223

We should add logging there to see the output of the `npm install`, most certainly when there is error output.

**Comment by b4Beta** [comment] 2017-08-24 07:50
I was able to recreate this issue by adding a space after the version number in package.json
Original `"version": "1.0.0"`
Broken  "version": "1.0.1 "`

Removing the " " allowed a successful zapier push
Adding a " " recreated the issue

**Comment by FokkeZB** [comment] 2017-08-24 08:01
Excellent @b4Beta!

@biaoqianwo could you verify that your `package.json`'s `version` has a proper version with no space following the `version` and check other values are OK as well? Feel free to share the file contents here so that I can double-check.

**Comment by FokkeZB** [comment] 2017-08-24 08:04
@b4Beta later added:

> The Dev version had a space after the version number. This causes `zapier validate` to fail, and on `zapier push` with the error we are discussing. Adding/removing the space duplicates and resolves the issue.

I can confirm this:

```
$ zapier validate

Validating project locally.
┌──────────────────────────────────────────────────────────────────────────┐
│ = 1 =                                                                    │
│     Property │ App.version                                               │
│     Message  │ does not match pattern "^[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{ │
│              │ 1,3}$"                                                    │
│     Links    │ https://github.com/zapier/zapier-platform-schema/blob/v0. │
│              │ 10.2/docs/build/schema.md#versionschema                   │
└──────────────┴───────────────────────────────────────────────────────────┘
Your app is structurally invalid. Address concerns and run this command again.
You're performing commands on Node v7.10.0, but Zapier runs your code on v6.10.2. The version numbers must match. See https://zapier.github.io/zapier-platform-cli/index.html#requirements for more info.

Checking app style.
No style errors found during validation routine.
Your app looks great!

mbp-van-fokke:zapier-platform-app-fields fokkezb$ zapier push
Preparing to build and upload your app.

  Copying project to temp directory ⠃ done!
  Installing project dependencies ⠃ done!
  Applying entry point file ⠰

Error! : File /private/var/folders/gq/qh827x1s22x7l0t08vb2wln80000gn/T/zapier-7d8d8aa8/node_modules/zapier-platform-core/include/zapierwrapper.js not found.
(Use --debug flag and run this command again to get more details.)
```

When you do `zapier push` it should validate as part of that process - which it seems to do not.

**Comment by biaoqianwo** [comment] 2017-08-24 08:38
I solve it by move 'C:\Users\allen\zapier' to 'C:\Users\Public\zapier'.
'allen' is my windows username.

**Comment by FokkeZB** [comment] 2017-08-24 09:05
@biaoqianwo good to hear that resolved it! If you can, could you copy it back to `C:\Users\allen\zapier` and try `zapier validate --debug` and `zapier push --debug` for me and paste the logs here or email them to contact@zapier.com with a mention of `https://github.com/zapier/zapier-platform-cli/issues/82`? That may help us in solving the bug preventing you from pushing from your own user folder.

**Comment by BrunoBernardino** [comment] 2017-09-05 13:44
@biaoqianwo can you please check if `3.0.1` fixes this for you?

**Comment by adAnserem** [comment] 2017-11-22 20:33
Hello
I have same problem. 
Both on example-app and my app
![screenshot_2](https://user-images.githubusercontent.com/23035105/33148464-1ab76d48-cfdd-11e7-9c12-44a6d54fd55b.jpg)

I also have empty temp "node_modules" folder 
![screenshot_3](https://user-images.githubusercontent.com/23035105/33148549-612e7992-cfdd-11e7-85d7-507ab56e6175.jpg)

**Comment by FokkeZB** [comment] 2017-11-23 07:29
Thanks @adAnserem. What is the `zapier-platform-core` version in your app's `package.json`?

**Comment by adAnserem** [comment] 2017-11-23 09:14
4.0.0 in my app and in example-app
![image](https://user-images.githubusercontent.com/23035105/33165400-bf6d0e28-d047-11e7-84e2-7f932dd0a652.png)

**Comment by FokkeZB** [comment] 2017-11-24 08:22
Thanks @adAnserem. Could you try running `zapier build --debug`?

**Comment by adAnserem** [comment] 2017-11-24 10:20
@FokkeZB you can find it on first screenshot

**Comment by FokkeZB** [comment] 2017-11-24 10:34
@adAnserem ah 🤦‍♂️ sorry for missing that.

@BrunoBernardino it looks like `npm i --production` never runs for this user. I'd expect something like:

```
Running npm install --production command in /private/var/folders/gq/qh827x1s22x7l0t08vb2wln80000gn/T/zapier-a3aeadb9:

⠉

⠤



⠘

added 35 packages in 3.903s

⠃ done!
```

> PS: Notice the broken spinner

**Comment by adAnserem** [comment] 2017-11-24 10:54
![image](https://user-images.githubusercontent.com/23035105/33207514-097a2ee2-d11f-11e7-910b-db10b96831b5.png)
@FokkeZB

**Comment by FokkeZB** [comment] 2017-11-24 12:03
That's very helpful @adAnserem! Would you mind sharing the `package.json` contents in that temporary folder?

**Comment by FokkeZB** [comment] 2017-11-24 12:04
O wait, please run the `npm(.cmd) install --production` one level higher, not in the `node_modules` folder. That is expected to fail.

**Comment by adAnserem** [comment] 2017-11-24 12:23
@FokkeZB there is not any files in temp folders, only empty "node_modules" folder

![image](https://user-images.githubusercontent.com/23035105/33210477-6e63c65e-d12b-11e7-9d8a-2cfd24d87294.png)

**Comment by FokkeZB** [comment] 2017-11-24 12:31
OK, that means `copyDir()` has failed without throwing an error:
https://github.com/zapier/zapier-platform-cli/blob/0bb81e1548086d217a3f5295dd43ff029ac0f077/src/utils/build.js#L229

`tmpDir` isn't known outside that build function so it's not cleaned up later but just never got any files.

We'll need to dive into:
https://github.com/zapier/zapier-platform-cli/blob/0bb81e1548086d217a3f5295dd43ff029ac0f077/src/utils/files.js#L81-L131

Thanks so far @adAnserem. We'll get back to you when we have a fix or further questions.

**Comment by W7PEA** [comment] 2017-12-12 20:19
Just a me too to let you know the node_modules not being copied is widely affecting folks.

zapier-platform-cli/4.1.0
node/v6.10.2

**Comment by FokkeZB** [comment] 2017-12-13 08:23
Thanks @W7PEA - we're looking into it - sorry for delay!

**Comment by eliangcs** [comment] 2017-12-14 13:58
@W7PEA @adAnserem I'm investigating this issue but unable to reproduce on my Windows 10 VM. Could you guys provide the source code of your apps? If you don't feel comfortable making it public, you can email me at chang-hung.liang@zapier.com. Thanks!

**Comment by adAnserem** [comment] 2017-12-15 11:18
@eliangcs i sent invite to your gitlab repository on your email

**Comment by eliangcs** [comment] 2017-12-15 12:32
@adAnserem I didn't get the invitation possibly because I didn't sign up GitLab with that email address. Could you send it again to eliang.cs@gmail.com?

**Comment by W7PEA** [comment] 2017-12-16 08:50
I had written ZERO additional code other than one of the samples. I spun up a linux VM and I'm unblocked, but that shouldn't be necessary.

**Comment by adAnserem** [comment] 2017-12-18 08:55
by the way, I also tried to build your examples, with same results

**Comment by eliangcs** [comment] 2017-12-18 09:58
@adAnserem I tried hard but still can't reproduce the issue. Could it be a permission issue? @biaoqianwo suggested earlier in this thread that moving the project to 'C:\Users\Public\' fixed the issue. Can you try it, too? And also, it may be useful if you can upload a screenshot of your Temp folder's permission info, like the following:

<img width="394" alt="screen shot 2017-12-18 at 17 56 59" src="https://user-images.githubusercontent.com/740461/34100271-ed5f77ec-e41c-11e7-87d5-1090f28bf798.png">

Thanks!

**Comment by adAnserem** [comment] 2017-12-19 13:02
@ eliangcs

I added full rights to the project folder personally for my user and looks like it fixes the problem :)
My admin user, the admins group has full rights to the project folder (c:\zapier), but using administrator rights requires UAC confirmation. And I did not give for a "users" group permission to the project folder for some reason.
So I think that the problem was created only by the UAC (or by me, sorry )
Later I will check more meticulously that everything works

**Comment by eliangcs** [comment] 2017-12-19 14:01
@adAnserem glad you're able to resolve the problem. With the info you provided, perhaps we can reproduce the issue and try to give users a better error message instead of just letting it crash.

**Comment by FokkeZB** [comment] 2018-03-29 07:27
@sisodiakaran thanks reporting! Do you mean that a CLI app that has a space in its `package.json` `name` causes this issue?

**Comment by sisodiakaran** [comment] 2018-03-30 02:09
@FokkeZB Yes, at least in my case this was the culprit.

**Comment by FokkeZB** [comment] 2018-03-30 07:44
@sisodiakaran I tried to reproduce this but found that both on Mac as well on Windows I get the following error when I try to run `zapier build` or `zapier push` on an app that has a space in the `package.json` `name` (I used `my app`):

```
$ zapier build
Building project.

  Copying project to temp directory ⠃ done!
  Installing project dependencies ⠃ done!
  Applying entry point file ⠆

Error! : File /private/var/folders/gq/qh827x1s22x7l0t08vb2wln80000gn/T/zapier-64909ce0/node_modules/zapier-platform-core/include/zapierwrapper.js not found.
(Use --debug flag and run this command again to get more details.)
```

So I actually don't even arrive at the point where it finished the builds. How exactly did you end up getting successful build with a space in the package name?

**Comment by sisodiakaran** [comment] 2018-03-30 17:56
@FokkeZB As I said in my solution "Once I removed the space all back ok again.". So basically I updated my package.json file and removed the `space` from the name ie: `my app` to `my-app`.

**Comment by FokkeZB** [comment] 2018-04-01 18:55
Thanks for confirming @sisodiakaran - odd that I couldn't reproduce that. However, once we have #288 in place you should see the actual NPM error causing the empty `node_modules` in such a case.

**Comment by eliangcs** [comment] 2018-04-02 03:29
#288 will be shipped in the next release. ETA: April 19.

**Comment by xavdid** [comment] 2019-05-29 20:50
this shipped, closing

**Closed by xavdid** 2019-05-29 20:50 UTC
Labels: bug
