### ISSUE TITLE
altersDynamicFields property doesn't have an immediate effect on triggers

### ISSUE THREAD

**Issue by jackjacek** [zapier/zapier-platform-cli#162] opened 2017-10-18 08:40 UTC
Neither of those seem to have an effect in **Trigger**:

**Trigger** alone:
```    inputFields: [
      {key: 'filter', required: false, label: 'Filter', choices: {a: 'Group', b: 'Creator', c: 'Participant'}, altersDynamicFields: true},
      function (z, bundle) {
        z.console.log('bundle.inputData.filter', bundle.inputData.filter)
        if (bundle.inputData.filter === 'a') {
          return [{key: 'tag', required: false, label: 'Group', dynamic: 'groupList.id.name'}]
        } else if (bundle.inputData.filter === 'b') {
          return [{key: 'creator', required: false, label: 'Creator', dynamic: 'creatorList.id.name'}]
        } else if (bundle.inputData.filter === 'c') {
          return [{key: 'user', required: false, label: 'Participant', dynamic: 'userList.id.name'}]
        }
        return []
      }
    ],
```

**Resource & Trigger** combination
```
const listChoices = (z, bundle) => {
  const choices = [{id: 'a', name: 'Group'}, {id: 'b', name: 'Creator'}, {id: 'c', name: 'Participant'}]
  return choices
}

module.exports = {
  key: 'listChoices',
  noun: 'Choices',
  list: {
    operation: {
      perform: listChoices
    },
    display: {
      label: 'Choices',
      description: 'Lists choices.',
      hidden: true
    }
  }
}
(...)

module.exports = {
(...)
  operation: {
    inputFields: [
      {key: 'filter', required: false, label: 'Filter', dynamic: 'listChoices.id.name', altersDynamicFields: true},
      function (z, bundle) {
        z.console.log('bundle.inputData.filter', bundle.inputData.filter)
        if (bundle.inputData.filter === 'a') {
          return [{key: 'tag', required: false, label: 'Group', dynamic: 'groupList.id.name'}]
        } else if (bundle.inputData.filter === 'b') {
          return [{key: 'creator', required: false, label: 'Creator', dynamic: 'creatorList.id.name'}]
        } else if (bundle.inputData.filter === 'c') {
          return [{key: 'user', required: false, label: 'Participant', dynamic: 'userList.id.name'}]
        }
        return []
      }
    ],
(...)
}
```

The only way to have dynamic dropdowns appear in the UI is to either:
a) Hit button '**Continue**' and navigate back to '**Edit Options**' using sidebar
b) '**Refresh**' upon selecting one of the choices (_Group_, _Creator_, _Participant_)

Hope this helps

**Comment by klichukb** [comment] 2017-11-12 23:39
Also experiencing this problem. I'm specifically on "Create" flow. Need to click "Refresh fields" manually, whereas documentation implies pretty obviously it should be done automatically:

> This informs the Zapier UI that whenever the value of that field changes, fields need to be recomputed
https://zapier.github.io/zapier-platform-cli/#customdynamic-fields

**Comment by BrunoBernardino** [comment] 2017-11-13 16:46
@jackjacek I'm really sorry about the late reply here. Can you please try adding a `dynamic` property (can be a trigger that returns nothing) to your first field and seeing if it works? I'm suspecting some bug with non-dynamic dropdowns there.

I know `altersDynamicFields` was initially fixed at https://github.com/zapier/zapier-platform-cli/issues/85 but maybe it was only for dynamic fields.

**Comment by jackjacek** [comment] 2017-11-13 16:54
@BrunoBernardino I believe my second example is a display of using `dynamic` property?

**Comment by BrunoBernardino** [comment] 2017-11-13 17:12
Ah, you're right, sorry. I'll test this locally tomorrow and see if I can replicate the issue.

**Comment by BrunoBernardino** [comment] 2017-11-14 16:13
@jackjacek I'm not able to replicate this locally (with or without the `dynamic` thing works the same). Would you mind sending an email over to partners@zapier.com with your app id and a potential Zap id you've been testing this on? If you're comfortable sharing those here, it's also fine.

@klichukb that also applies to you.

Thank you so much for your patience!

**Comment by BrunoBernardino** [comment] 2017-11-21 09:40
Are you still having this issue? If not, I'd like to close this, otherwise, I'd like to figure out how to replicate and fix this.

**Comment by klichukb** [comment] 2017-11-22 11:28
I personally did not use dropdown, was hoping to get it working for regular text field.

But since this thread gave me the idea that I actually need dropdown, i used it -- for me fields started working properly. But to be honest, loading further was pretty slow, provided that endpoint which returns fields on backend was pretty much hardcoded.

Thanks, functionally the issue is solved.

**Comment by BrunoBernardino** [comment] 2017-11-22 11:32
Thanks for the comment!

First loads after a push should take a few seconds while we're updating with the new code, but after that they should be in the realm of ~1-2s tops, especially if they're hardcoded.

**Comment by benzapier** [comment] 2017-12-01 18:19
I think I have an example that replicates this issue.  I started with the [Dynamic Dropdown](https://github.com/zapier/zapier-platform-example-app-dynamic-dropdown) example app, and changed the [existing inputFields](https://github.com/zapier/zapier-platform-example-app-dynamic-dropdown/blob/master/triggers/people.js#L45-L47) to contain this:

```js
    inputFields: [
      {key: 'species', type: 'string',  helpText: 'Species of person', dynamic: 'species.id.name', altersDynamicFields:true},
      function(z, bundle) {
        if (!bundle.inputData.species) {
          return [];
        }
        return [
             {key: 'foo1', label: 'Favorite Number', required: false, type: 'integer'},
             {key: 'foo2', label: 'Favorite Color', required: false, type: 'unicode'},
        ];        
      }
    ],
```


Here's a screen recording of the issue within the Zap Editor: http://recordit.co/tv0WUcMeXF

When the user leaves the "Trigger Fields" screen, and then returns to it, the input fields are rendered correctly.  Otherwise, it doesn't seem to matter how long the user waits at the Trigger Fields screen, the fields don't seem to refresh correctly.

**Comment by BrunoBernardino** [comment] 2017-12-04 16:31
Thanks @benzapier ! That helped!

I can confirm this problem is happening for **Triggers**. If anyone is experiencing this somewhere else, please let me know.

Indeed we have never supported custom fields in triggers (only "result custom fields" (i.e. `outputFields`)).

I'm looking into if we can/should support this, or document this impossibility.

**Comment by BrunoBernardino** [comment] 2017-12-08 07:28
This will really be fixed once https://github.com/zapier/zapier/pull/14657 ships (was auto-closed because of merging the PR).

**Closed** 2017-12-16 09:33 UTC
Labels: bug
